# Generated by Django 5.1.2 on 2024-10-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='form',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.category'),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option', to='form.option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='select',
            field=models.ManyToManyField(blank=True, max_length=255, null=True, related_name='select', to='form.option'),
        ),
        migrations.AddField(
            model_name='process',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.category'),
        ),
        migrations.AddField(
            model_name='process',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='question',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.process'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.question'),
        ),
    ]
