# Generated by Django 5.1.2 on 2024-10-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
