
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres  # Change this to your database name
      POSTGRES_USER: postgres    # Change this to your username
      POSTGRES_PASSWORD: postgres  # Change this to your password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network  

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge
    
volumes:
  postgres_data:
